--[[ This Source Code Form is subject to the terms of the Mozilla Public
     License, v. 2.0. If a copy of the MPL was not distributed with this
     file, You can obtain one at https://mozilla.org/MPL/2.0/. ]]

##[[
  TICO = {
    L = 'tinycoffee/build',
    I = {
      include = "tinycoffee/include",
      external = "tinycoffee/external"
    }
  }
]]

require 'output.tico'

local nelua_argc: cint <cimport, nodecl>
local nelua_argv: *[0]cstring <cimport, nodecl>

local config = tico.config_init('basic test', 640, 380, nelua_argc, nelua_argv)
tico.init(config)

while not tico.window_should_close() do -- main loop
  tico.update() -- update inputs, timers, ...

  -- [[ begin batch render [[
  tico.begin_draw()
  do
    tico.graphics_clear(tico.BG) -- clear screen with color

    tico.graphics_draw_text("my test text", 20, 20, tico.WHITE)

    if tico.input_key_down(tico.KEY.KEY_SPACE) then
      tico.graphics_draw_text("SPACE is down!", 20, 60, tico.WHITE)
    end
  end
  tico.end_draw()
  -- ]] finish batch render ]]
end

tico.terminate()
